config/routes.rb
Rails.application.routes.draw do

	get 'signup', to: 'users#new', as: 'signup'
	get 'login', to: 'sessions#new', as: 'login'
	get 'logout', to: 'sessions#destroy', as: 'logout'

	root to: 'properties#index'
	
	resources :properties, only: [:index]
	resources :sessions, only: [:new, :create, :destroy]

  resources :users do
  	resources :properties, except: [:index]
  end
end

app/models/property.rb
class Property < ActiveRecord::Base
	validates :address, presence: true
	validates :price, presence: true
	validates :bedroom, presence: true
	validates :bathroom, presence: true

	belongs_to :user

	has_attached_file :photo, styles: { medium: '300x300>' },
										url: "/assets/properties/:id/:style/:basename.:extension",
										path: ":rails_root/public/assets/properties/:id/:style/:basename.:extension"
										
	validates_attachment_content_type :photo, content_type: ['image/png', 'image/jpeg', 'image/jpg', 'image/gif']
end

app/models/user.rb
class User < ActiveRecord::Base
	validates :first_name, presence: true
	validates :last_name, presence: true
	validates :company, presence: true
	validates :work_phone, presence: true
	validates :cell_phone, presence: true
	validates :email, presence: true, uniqueness: true

	has_many :properties, dependent: :destroy

	has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

private
	def current_user
		@current_user ||= User.find(session[:user_id]) if session[:user_id]
	end

	def authorize
		if current_user.nil?
			flash[:alert] = "Not Authorized To View Page"
			redirect_to login_url
		end
	end

	helper_method :current_user
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
	before_action :authorize, except: [:index]

	def index
		@properties = Property.all
	end

	# def show
	# 	@user = User.find(params[:user_id])
	# 	@property = @user.properties.find(params[:id])
	# 	redirect_to user_path(@user)
	# end

	def new
		@user = User.find(params[:user_id])
		@property = @user.properties.new
	end

	def create
		@user = User.find(params[:user_id])
		@property = @user.properties.new(property_params)
		if @property.save
			respond_to do |format|
				format.html { redirect_to new_user_property_path(@user) }
				format.js
			end
		else
			flash[:notice] = 'An Error Occurred. Please Try Input Again.'
			redirect_to user_path(@user)
		end
	end

	def edit
		@user = User.find(params[:user_id])
		@property = @user.properties.find(params[:id])
	end

	def update
		@user = User.find(params[:user_id])
		@property = @user.properties.find(params[:id])
		if @property.update(property_params)
			flash[:notice] = "Property Details Have Been Updated"
			respond_to do |format|
				format.html { redirect_to user_property_path(@user, @property) }
				format.js
			end
		else
			redirect_to user_path(@user)
		end
	end

	def destroy
		@user = User.find(params[:user_id])
		@property = @user.properties.find(params[:id])
		@property.destroy
		flash[:notice] = "The Property Has Been Deleted"
		redirect_to user_path(@user)
	end

private
	def property_params
		params.require(:property).permit(:address, :price, :bedroom, :bathroom, :photo, :email, :password, :password_confirmation)
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
		respond_to do |format|
			format.html { redirect_to login_path }
			format.js
		end
	end

	def create
		@user = User.find_by_email(params[:email])
		if @user && @user.authenticate(params[:password])
			respond_to do |format|
				format.html { redirect_to root_url }
				format.js
				session[:user_id] = @user.id
				flash[:notice] = 'Logged In'
			end	
		else
			flash[:alert] = 'Email or password is invalid'
			render 'new'
		end
	end

	def destroy
		session[:user_id] = nil
		flash[:notice] = "Logged Out"
		redirect_to root_url
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authorize, only: [:edit, :update, :destroy]
	
	def index
		@users = User.all
	end

	def show
		@user = User.find(params[:id])
		render 'users/show.html.erb'
	end

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			session[:user_id] = @user.id
			flash[:notice] = 'Your New Account Has Been Created'
			redirect_to user_path(@user)
		else
			render 'users/new.html.erb'
		end
	end

	def edit
		@user = User.find(params[:id])
		render 'users/edit.html.erb'
	end

	def update
		@user = User.find(params[:id])
		if @user.update(user_params)
			flash[:notice] = 'Your Account Has Been Updated'
			redirect_to user_path(@user)
		else
			render 'users/edit.html.erb'
		end
	end

	def destroy
		@user = User.find(params[:id])
		@user.delete
		flash[:notice] = 'Your Account Has Been Removed'
		redirect_to users_path
	end

private
	def user_params
		params.require(:user).permit(:first_name, :last_name, :company, :work_phone, :cell_phone, :email, :password, :password_confirmation)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
	<ul>
		<% object.errors.full_messages.each do |message| %>
			<li><%= message %></li>
		<% end %>
	</ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<div class='flash-alert'><%= flash[:alert] %></div>
	<div class='flash-notice'><%= flash[:notice] %></div>

	<% if current_user %>
		<span id='logged-true'>
			logged in as <%= current_user.email %>
			<%= link_to 'log out', logout_path %>
		</span>
	<% else %>
		<span id='signup-login'>
			<%= link_to 'signup', signup_path %> or
			<%= link_to 'log in', login_path, remote: true %>
		</span>
	<% end %>

	<%= yield %>

</body>
</html>

app/views/properties/_form.html.erb
<div class='property-form'>
	<%= form_for [@user, @property], html: { multipart: true }, id: 'property-form', remote: true do |f| %>
		<%= f.label :address %>
		<%= f.text_field :address %>

		<%= f.label :price %>
		<%= f.text_field :price %>

		<%= f.label :bedroom %>
		<%= f.text_field :bedroom %>

		<%= f.label :bathroom %>
		<%= f.text_field :bathroom %>

		<%= f.file_field :photo %>

		<%= f.submit %>
	<% end %>
</div>

app/views/properties/_property.html.erb
<div>
	<%= image_tag property.photo.url(:medium) %>
	<%= property.address %>
	<%= property.price %>
	<%= property.bedroom %>
	<%= property.bathroom %>
	<p><%= link_to 'Edit Property', edit_user_property_path(@user, property), id: 'edit-property', remote: true %></p>
	<p><%= link_to 'Delete Property', user_property_path(@user, property), 
						data: { confirm: 'Are you sure you want to delete this property?',
										method: 'delete'
										} 
	%></p> 
</div>

app/views/properties/create.js.erb
$('.new_property').remove();
$('.property-add').show();
$('.property-list').append('<%= j render "properties/property", property: @property %>');

app/views/properties/edit.js.erb
$('#edit-property').hide().after('<%= j render "form" %>');

app/views/properties/index.html.erb
<% content_for :title, 'Index | Padmapper' %>

<h1>Index</h1>

<% @properties.each do |property| %>
	<p><%= property.address %></p>
<% end %>

app/views/properties/new.html.erb
<% content_for :title, 'New Property | Padmapper' %>

<%= render 'layouts/errors', object: @property %>

<%= render 'form' %>

app/views/properties/new.js.erb
$('.property-add').hide().after("<%= j render 'form' %>");

app/views/properties/update.js.erb
$('.edit_property').hide();
$('#edit-property').show();
$('.propert-list').append('<%= j render "properties/property", property: @property');

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
	<%= f.label :first_name %>
	<%= f.text_field :first_name %>

	<%= f.label :last_name %>
	<%= f.text_field :last_name %>

	<%= f.label :company %>
	<%= f.text_field :company %>

	<%= f.label :work_phone %>
	<%= f.text_field :work_phone %>

	<%= f.label :cell_phone %>
	<%= f.text_field :cell_phone %>

	<%= f.label :email %>
	<%= f.text_field :email %>

	<%= f.label :password %>
	<%= f.password_field :password %>

	<%= f.label :password_confirmation %>
	<%= f.password_field :password_confirmation %>

	<%= f.submit %>
<% end %>

app/views/users/edit.html.erb
<% content_for :title, 'Edit | Padmapper' %>

<%= render 'layouts/errors', object: @user %>
<%= render 'form' %>

app/views/users/index.html.erb
<% content_for :title, 'Index | Padmapper' %>

<% @users.each do |user| %>
	<p><%= user.first_name %> <%= user.last_name %>
<% end %>

app/views/users/new.html.erb
<% content_for :title, "New User | Padmapper" %>

<%= render 'layouts/errors', object: @user %>
<%= render 'form' %>

app/views/users/show.html.erb
<% content_for :title, 'User | Padmapper' %>

<h1><%= @user.first_name %> <%= @user.last_name %></h1>
<h4><%= @user.company %></h4>

<p>Office Contact: <%= @user.work_phone %></p>
<p>Mobile Contact: <%= @user.cell_phone %></p>

<%= link_to 'Add A Property', new_user_property_path(@user), class: 'property-add', remote: true %>

<div class='property-list'>
	<%= render partial: 'properties/property', collection: @user.properties %>
</div>

<p><%= link_to 'Delete Account', user_path(@user), 
									data: { confirm: 'Are you sure you want to delete this account?',
													method: 'delete'}  
%></p>		